export function cursorrulesTemplate({ projectName }) {
  return `# ${projectName} — Cursor Rules (generated by drykit)

## Component Registry

Read \`.drykit/fingerprint.md\` at the start of every session.
Before creating any component, hook, or utility — check if it already exists.
If fingerprint routes you to \`front.md\` or \`api.md\` — read that file.

## Scan check (REQUIRED before any UI/component work)

After reading fingerprint.md, check the stats line (e.g. "3 components, 2 hooks").
If it shows **0 components** or the file doesn't exist:
1. STOP — do not proceed with the task
2. Ask the user: "drykit scan hasn't been run yet (registry is empty). Should I run it now?"
3. If yes → run: \`npx drykit scan\`
4. Re-read \`.drykit/fingerprint.md\` and continue

## Rules
- NEVER create a component without checking the registry
- If a component exists with variants — use a variant, don't create new
- If you must create new — run: drykit add <Name>
- After creating — verify registry.json was updated

## Behavioral Guardrails
- Do NOT build, commit, or push without explicit user command
- Do NOT edit files outside the current task scope
- Do NOT add dependencies without asking first
- Check TypeScript types before reporting task as done
- One session = one goal. When done, say "done" and wait
- NEVER hardcode API keys, tokens, or passwords — use .env.local
`;
}
