import fs from 'node:fs';
import path from 'node:path';
import { configTemplate } from '../templates/config.mjs';
import { registryTemplate } from '../templates/registry.mjs';
import { schemaTemplate } from '../templates/schema.mjs';
import { agentsMdTemplate } from '../templates/agents-md.mjs';
import { claudeMdDrykitSection } from '../templates/claude-md.mjs';
import { kiroSteeringAlways, kiroSteeringFront } from '../templates/kiro-steering.mjs';
import { kiroScannerAgent, kiroArchitectAgent } from '../templates/kiro-agents.mjs';
import { claudeScannerAgent, claudeArchitectAgent } from '../templates/claude-agents.mjs';
import { preCommitTemplate } from '../templates/pre-commit.mjs';
import { appendSectionIfMissing } from '../core/updater.mjs';

function mkdirp(dir) { fs.mkdirSync(dir, { recursive: true }); }

function writeIfMissing(filePath, content) {
  if (fs.existsSync(filePath)) return false;
  mkdirp(path.dirname(filePath));
  fs.writeFileSync(filePath, content);
  return true;
}

async function promptUser() {
  const prompts = (await import('prompts')).default;
  const response = await prompts([
    { type: 'text', name: 'projectName', message: 'Project name:', initial: path.basename(process.cwd()) },
    { type: 'text', name: 'stack', message: 'Stack (e.g. React 19, Next.js 15):', initial: 'React 19' },
    { type: 'text', name: 'css', message: 'CSS framework (e.g. Tailwind 4, none):', initial: 'Tailwind 4' },
    { type: 'confirm', name: 'typescript', message: 'TypeScript?', initial: true },
    { type: 'select', name: 'ai', message: 'AI tools:', choices: [
      { title: 'Both (Claude Code + Kiro)', value: 'both' },
      { title: 'Claude Code only', value: 'claude' },
      { title: 'Kiro only', value: 'kiro' },
    ]},
    { type: 'text', name: 'componentsDir', message: 'Components directory:', initial: 'src/components' },
  ]);
  return response;
}

export async function runInit({ root = process.cwd(), answers = null } = {}) {
  const a = answers || await promptUser();
  const { projectName, stack, css, typescript, ai, componentsDir } = a;

  const useClaude = ai === 'both' || ai === 'claude';
  const useKiro = ai === 'both' || ai === 'kiro';

  // drykit.config.mjs
  writeIfMissing(path.join(root, 'drykit.config.mjs'), configTemplate({ componentsDir, projectName, stack: `${stack}${css !== 'none' ? ' + ' + css : ''}` }));

  // registry.json + schema
  const regDir = path.join(root, 'src');
  mkdirp(regDir);
  writeIfMissing(path.join(regDir, 'registry.json'), registryTemplate());
  writeIfMissing(path.join(regDir, 'registry.schema.json'), schemaTemplate());

  // .drykit/ fingerprint files
  const drykitDir = path.join(root, '.drykit');
  mkdirp(drykitDir);
  writeIfMissing(path.join(drykitDir, 'fingerprint.md'),
    `# ${projectName} | ${stack}${css !== 'none' ? ' + ' + css : ''}\n# Fingerprint: ${new Date().toISOString()} (auto-generated by drykit scan)\n\n## Routing\n- Building UI/component → read .drykit/front.md\n- Building API/endpoint → read .drykit/api.md\n\n## Rules\n- ALWAYS read the relevant file BEFORE creating anything\n- If something exists — use it, don't create new\n- New component? Check variants of existing ones first\n`);
  writeIfMissing(path.join(drykitDir, 'front.md'), '# Frontend | 0 components, 0 hooks, 0 utils\n');
  writeIfMissing(path.join(drykitDir, 'api.md'), '# API | 0 procedures, 0 schemas\n');

  // AGENTS.md (Kiro reads natively, always)
  writeIfMissing(path.join(root, 'AGENTS.md'), agentsMdTemplate({ projectName }));

  // CLAUDE.md
  if (useClaude) {
    appendSectionIfMissing(
      path.join(root, 'CLAUDE.md'),
      '## drykit',
      claudeMdDrykitSection({ projectName })
    );
  }

  // .kiro/steering/
  if (useKiro) {
    const steeringDir = path.join(root, '.kiro', 'steering');
    mkdirp(steeringDir);
    writeIfMissing(path.join(steeringDir, 'drykit.md'), kiroSteeringAlways());
    writeIfMissing(path.join(steeringDir, 'drykit-front.md'), kiroSteeringFront());

    const kiroAgentsDir = path.join(root, '.kiro', 'agents');
    mkdirp(kiroAgentsDir);
    writeIfMissing(path.join(kiroAgentsDir, 'drykit-scanner.json'), kiroScannerAgent());
    writeIfMissing(path.join(kiroAgentsDir, 'drykit-architect.json'), kiroArchitectAgent());
  }

  // .claude/agents/
  if (useClaude) {
    const claudeAgentsDir = path.join(root, '.claude', 'agents');
    mkdirp(claudeAgentsDir);
    writeIfMissing(path.join(claudeAgentsDir, 'drykit-scanner.md'), claudeScannerAgent());
    writeIfMissing(path.join(claudeAgentsDir, 'drykit-architect.md'), claudeArchitectAgent());
  }

  // .husky/pre-commit
  const huskyDir = path.join(root, '.husky');
  mkdirp(huskyDir);
  const hookPath = path.join(huskyDir, 'pre-commit');
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf8');
    if (!existing.includes('drykit')) {
      fs.writeFileSync(hookPath, existing.trimEnd() + '\n\n# drykit check\nnpx drykit check --ci\n');
    }
  } else {
    writeIfMissing(hookPath, preCommitTemplate());
  }

  // docs dir
  mkdirp(path.join(root, 'docs', 'components'));

  // Update package.json scripts (if exists)
  const pkgPath = path.join(root, 'package.json');
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    pkg.scripts = pkg.scripts || {};
    const drykitScripts = {
      'drykit:scan': 'drykit scan',
      'drykit:check': 'drykit check',
      'drykit:docs': 'drykit docs',
    };
    let changed = false;
    for (const [k, v] of Object.entries(drykitScripts)) {
      if (!pkg.scripts[k]) { pkg.scripts[k] = v; changed = true; }
    }
    if (changed) fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  }

  console.log(`\n✓ drykit initialized in ${root}`);
  console.log(`  Run: drykit scan — to populate the registry`);
}

export default async function init(args) {
  await runInit();
}
