export function generateFingerprint(registry, config, projectName, stack, changedLines) {
  const ts = new Date().toISOString();
  const compCount = registry.components.length;
  const hookCount = registry.hooks.length;
  const utilCount = registry.utils.length;
  const routeCount = (registry.routes || []).reduce((s, r) => s + (r.routes?.length || 0), 0);
  const schemaCount = (registry.schemas || []).length;

  let md = `# ${projectName} | ${stack}
# Fingerprint: ${ts} (auto-generated by drykit scan)

## Stats
${compCount} components, ${hookCount} hooks, ${utilCount} utils, ${routeCount} routes, ${schemaCount} schemas

## Routing
- Building UI/component → read .drykit/front.md
- Building API/endpoint → read .drykit/api.md

## Rules
- ALWAYS read the relevant file BEFORE creating anything
- If something exists — use it, don't create new
- New component? Check variants of existing ones first
`;

  if (changedLines && changedLines.length > 0) {
    md += `\n## Changed (last 7 days)\n`;
    for (const line of changedLines) {
      md += `${line}\n`;
    }
  }

  return md;
}

export function generateFrontMd(registry) {
  const compCount = registry.components.length;
  const hookCount = registry.hooks.length;
  const utilCount = registry.utils.length;

  let md = `# Frontend | ${compCount} components, ${hookCount} hooks, ${utilCount} utils\n`;

  if (compCount > 0) {
    md += `\n## Components\n`;
    for (const c of registry.components) {
      const vars = c.variants?.length ? ` [${c.variants.join('|')}]` : '';
      md += `${c.name}${vars} → ${c.path}\n`;
      if (c.props && Object.keys(c.props).length > 0) {
        md += `  props: ${Object.keys(c.props).join(', ')}\n`;
      }
      if (c.dependencies?.length > 0) {
        md += `  deps: ${c.dependencies.join(', ')}\n`;
      }
    }
  }

  if (hookCount > 0) {
    md += `\n## Hooks\n`;
    for (const h of registry.hooks) {
      const deps = h.dependencies?.length ? ` (deps: ${h.dependencies.join(', ')})` : '';
      md += `${h.name}${deps} → ${h.path}\n`;
    }
  }

  if (utilCount > 0) {
    md += `\n## Utils\n`;
    for (const u of registry.utils) {
      md += `${u.name} → ${u.path}\n`;
    }
  }

  // Wiring: components that depend on other registered items
  const allNames = new Set([
    ...registry.components.map(c => c.name),
    ...registry.hooks.map(h => h.name),
    ...registry.utils.map(u => u.name),
  ]);
  const wirings = [];
  for (const c of registry.components) {
    const internal = (c.dependencies || [])
      .map(d => { const parts = d.split('/'); return parts[parts.length - 1]; })
      .filter(d => allNames.has(d));
    if (internal.length > 0) wirings.push(`${c.name} → ${internal.join(', ')}`);
  }
  if (wirings.length > 0) {
    md += `\n## Wiring\n`;
    for (const w of wirings) md += `${w}\n`;
  }

  return md;
}

export function generateApiMd(registry) {
  const routeCount = (registry.routes || []).reduce((s, r) => s + (r.routes?.length || 0), 0);
  const schemaCount = (registry.schemas || []).length;

  let md = `# API | ${routeCount} procedures, ${schemaCount} schemas\n`;

  if ((registry.routes || []).length > 0) {
    md += `\n## Routes\n`;
    for (const r of (registry.routes || [])) {
      for (const proc of (r.routes || [])) {
        md += `${r.name}.${proc.name} (${proc.method})\n`;
      }
    }
  }

  if (schemaCount > 0) {
    md += `\n## Schemas\n`;
    for (const s of (registry.schemas || [])) {
      md += `${s.name} → ${s.path} (${s.fields.join(', ')})\n`;
    }
  }

  return md;
}
